### PR TITLE
Shuffle command changes

### PR DESCRIPTION
**Pull request by matthew-groth**
Shuffle command now displays a different icon and text depending on the current state.

I added the .alfredworkflow because I do not know what you did to not have it in the master repository. Is it hiding somewhere or _is there some other way to export a workflow_?

The icon is not great, but perhaps someone with more experience can create a better one to indicate that shuffle is OFF.

### CODE REVIEW

**Comment by vdesabou** [comment]
Sorry for late reply.

I don't understand your PR, you only added an image Notshuffle.png, where in the code you changed something to use that image?

The alfredworkflow file is located on Packal, so that people can use Packal to update the workflow, that's why it is not included in the Github repository.

What exactly do you want to achieve here ?

**Comment by matthew-groth** [comment]
No worries. My code change is located in the workflow itself, which you can download from my repo. I didn't figure out et how the Alfred workflow filesystem works yet. So I don't know of an easier way to update a single workflow item other than to just share my entire exported workflow.

The change is the 'shuffle' command, as I explained above. Unless theres a better way, I guess you have to make a backup of your workflow and import my workflow in order to see the change.

**Comment by vdesabou** [comment]
Well, I have downloaded the workflow from here https://github.com/matthew-groth/alfred-spotify-mini-player/blob/master/Spotify%20Mini%20Player.alfredworkflow

But I can't see any code change related to Notshuffle.png.

So please do a proper PR or explain me what you want to do with this Notshuffle.png, as it is still unclear to me

**Comment by matthew-groth** [comment]
I redownloaded the file you just linked, and imported it into Alfred. 

The change is there. You can see the code change inside the Script Filter titled "{vsr:c_shuffle}". You can see it in action by typing the shuffle command. It will tell you whether or not you are currently shuffling.

**Comment by vdesabou** [comment]
Ok I undertand what you did. I've opened issue https://github.com/vdesabou/alfred-spotify-mini-player/issues/186

Let's close this Pull Request as it can be merged and follow up on the issue.

**Pull request closed without merging**
